### ISSUE TITLE
[Docs - Quickstart] - Requesting swift

### ISSUE THREAD

**Issue by eob** [gitpod-io/website#1245] opened 2021-11-13 12:11 UTC
Hello!

We develop with server-side Swift and are wondering if you would consider supporting! It's not broadly known but Swift works just fine on linux.

Here is an example from GH Codespaces (I haven't tried this) that might be useful to see:

https://github.com/taki-on/swift_codespaces

**Comment by Siddhant-K-code** [comment] 2022-10-07 16:41
duplicate of https://github.com/gitpod-io/website/issues/1750

**Closed by Siddhant-K-code** 2022-10-07 16:41 UTC
Labels: section: docs, section: quickstarts, team: DCS
