### ISSUE TITLE
several screencast preview images are misaligned

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#1159] opened 2021-10-27 06:30 UTC
On several screencast images the logo falling out
<img width="426" alt="Bildschirmfoto 2021-10-27 um 08 29 01" src="https://user-images.githubusercontent.com/46345125/139011679-b39c41b5-9802-43a3-8728-d858042a6872.png">

**Comment by nisarhassan12** [comment] 2021-12-08 20:11
I'm going to close this as I'm unable to reproduce this I tested on Firefox, Safari and Google on Desktop and Firefox, Brave and Chrome on mobile.

I think it is either already addressed or somehow some CSS failed to load maybe. Please re-open if you see this issue again. Thanks

**Closed by nisarhassan12** 2021-12-08 20:11 UTC
Labels: bug
