### ISSUE TITLE
[Docs Enhacement - New Feature]: Add an easier method of embedding tweets

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/website#2323] opened 2022-06-28 14:14 UTC
### Describe your feature request

Like the `youtube: id` plugin, it would be nice to have a similar method of embedding tweets within our markdown files without having to use raw HTML.

### User impact

Easier to embed tweets.

**Comment by Cahllagerfeld** [comment] 2022-06-28 14:53
Additional Resource: https://www.swyx.io/the-hard-problem-of-rendering-tweets/

**Comment by mikenikles** [comment] 2022-07-12 05:25
Duplicate of #400

**Closed by mikenikles** 2022-07-12 05:25 UTC
Labels: docs-enhancement
