### ISSUE TITLE
Make 404 page friendly (and Gitpod branded)

### ISSUE THREAD

**Issue by shaal** [gitpod-io/website#1517] opened 2022-01-19 17:24 UTC
### Bug description

I think this is a new error, I noticed it only yesterday.
When going to a page that doesn't exist on www.gitpod.io (ie. https://www.gitpod.io/this-is-404-page), you'll see this page -
![image](https://user-images.githubusercontent.com/22901/150181903-b1f3654c-6565-41c5-b6b4-de7bd9335505.png)

### Steps to reproduce

Go to any URL that doesn't exist
ie. https://www.gitpod.io/this-is-404-page

### Expected behavior

Display a "Gitpod 404" branded page

**Comment by axonasif** [comment] 2022-01-21 14:13
> Hey @shaal, this would be better in the website repo. Can you close this and raise it there? https://github.com/gitpod-io/website

We can always transfer issues 😉

**Comment by shaal** [comment] 2022-01-21 15:18
Thank you @axonasif

**Comment by pawlean** [comment] 2022-01-21 18:20
> > Hey @shaal, this would be better in the website repo. Can you close this and raise it there? https://github.com/gitpod-io/website
> 
> We can always transfer issues 😉

WOAH! I had no idea you could do this. 😂 Thanks for the daily lessons @axonasif!

**Comment by Cahllagerfeld** [comment] 2022-01-24 12:03
Is this a duplicate of #1479?

**Comment by shaal** [comment] 2022-01-24 19:13
@Cahllagerfeld in the video of #1479 it looks like the same error that I saw.

**Comment by axonasif** [comment] 2022-01-25 15:51
> WOAH! I had no idea you could do this. 😂 Thanks for the daily lessons @axonasif!

I didn't know either, I just saw some other Gitpodders to be doing this, so I was like: _Let's do this thing_  😂

**Comment by Siddhant-K-code** [comment] 2022-01-29 15:28
I think, we can continue on #1479  :D

**Closed** 2022-01-30 18:49 UTC
Labels: enhancement
