### ISSUE TITLE
500 error when accessing https://www.gitpod.io/docs

### ISSUE THREAD

**Issue by shaal** [gitpod-io/website#377] opened 2021-04-16 04:38 UTC
### Bug description

The URL https://www.gitpod.io/docs (or any other direct link to documentation) cannot be accessed directly and results in a 500 error.
The workaround is going to any other page (like the homepage), and then click on 'Docs' on the menu.

### Steps to reproduce

Open https://www.gitpod.io/docs in your browser, you'll get a 500 error.
![image](https://user-images.githubusercontent.com/22901/114972137-e6fce000-9e4b-11eb-8821-bbb63b103929.png)

### Expected behavior

I expect to be able to open directly any page in documentation.

**Comment by nisarhassan12** [comment] 2021-04-16 06:32
Thanks, @shaal for reporting this. I'm unable to reproduce this. 
![Peek 2021-04-16 11-29](https://user-images.githubusercontent.com/46004116/114981205-0ffe8e80-9ea7-11eb-9b1c-f1a4d5918718.gif)

Can you please share screenshots of the Network tab and the browser console after you hard reload the docs page?

**Comment by AlexTugarev** [comment] 2021-04-16 09:13
@nisarhassan12, I've seen the same error yesterday. 

Could it be, that during a deployment/update of the website the service is unavailable?

**Comment by mikenikles** [comment] 2021-04-16 11:48
I can reproduce it, although not reliably. It happened regularly with Firefox on MacOS, but a few minutes later it worked. Same for Brave on Android, broken for 10 or so reloads, then paused for a few minutes and retried successfully.

I suspected a new deployment as well at first, but a full page reload should work regardless of whether a deployment happened recently. I'll dig a bit deeper to see what's going on.

**Comment by mikenikles** [comment] 2021-04-16 14:54
Hey @shaal, could you clear your local cache and give www.gitpod.io/docs another go please?

I ended up upgrading our application framework (PR #379) as there were a few recent bug fixes that allowed me to switch to static pages rather than server-side rendered. I _suspect_ we had an issue with SSR in a previous deployment.

**Comment by ghuntley** [comment] 2021-04-19 01:13
Gitpod needs to decide what to do about `www.gitpod.io` (the website) and `gitpod.io` (the app). Apologies @shaal, know that I also share this frustration and run into it when sharing links on social media. Google Chrome flattens `www.gitpod.io` into `gitpod.io` which also exacerbates the problem. 

The upstream problem is https://github.com/gitpod-io/gitpod/issues/3898.

**Comment by shaal** [comment] 2021-04-24 20:24
Somewhat related? going to https://gitpod.io/docs (without 'www' prefix) results in 404 error.

Same with -
https://gitpod.io/features
https://gitpod.io/pricing
https://gitpod.io/blog
https://gitpod.io/docs
https://gitpod.io/careers

I think the only way to get to these URLs, is entering them manually.

**Comment by mikenikles** [comment] 2021-04-24 22:46
That's something I've ran into myself. We have conversations among the team on how to improve that user experience.

It comes down to the following URLs and their use:
* https://www.gitpod.io: The marketing website with the links you mentioned.
* https://gitpod.io: The actual Gitpod product.

An idea is to move the marketing site to https://about.gitpod.io to avoid the confusion with www and the root domain.

**Comment by nisarhassan12** [comment] 2021-05-25 11:34
Closing this as it seems to be fixed by https://github.com/gitpod-io/website/pull/394 Please re-open if you en counter the issue again. Thanks

**Comment by nisarhassan12** [comment] 2021-11-23 16:13
Reopening as it was reported again internally on Slack [here](https://gitpod.slack.com/archives/C01KGM9ETU6/p1637336132133700).

**Closed** 2022-01-20 09:29 UTC
Labels: section: docs
