### ISSUE TITLE
error messaging when loading /blog

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#3310] opened 2023-01-26 14:57 UTC
Sometimes when opening /blog I get a 500 error message.

When refreshing the page I almost always get an error message. See recording

https://user-images.githubusercontent.com/46345125/214868368-444534a6-a9f7-47af-bcb5-f7fa0ccbd3ed.mov

I can only reproduce the issue on Chrome. On Safari it seems to work fine

**Comment by Siddhant-K-code** [comment] 2023-01-27 12:03
I tried to reproduce this error. No Luck 😞 

Seems to work fine for me (even on different Chrome versions, tested using Browserstack) & on mobile devices also.

I even try to Repro. this with a Permission policy warning (by selecting opt-out in the cookie popup) It was still working:

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/55068936/215081803-061a4cd4-07b5-4421-a3d8-3d0b6c227777.png">


The only thing, I could think of is the network issue or there are some performance issues with svelte-kit version

**Comment by Siddhant-K-code** [comment] 2023-01-27 12:21
The issues seem to be fixed now. As I just merged a totally different PR which redeployed the whole website. Maybe there was some netlify adapter issue 😅

**Comment by Siddhant-K-code** [comment] 2023-01-28 10:53
Also, Related #3321, #3323

**Comment by Siddhant-K-code** [comment] 2023-01-28 11:03
This Bug was occurred due to #3239

**Closed** 2023-01-30 09:43 UTC
Labels: type: bug, team: website
