### ISSUE TITLE
Update self hosted page to reflect correct feature matrix

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website#918] opened 2021-09-01 15:26 UTC

**Comment by nisarhassan12** [comment] 2021-09-17 15:47
@JohannesLandgraf I'm closing this as it seems to be fixed in https://github.com/gitpod-io/website/commit/89ed15b41fde6272c643694e3098ee703bfb600f Please re-open If I misunderstood this and the issue is still relevant. Thanks

**Closed by nisarhassan12** 2021-09-17 15:47 UTC
