### ISSUE TITLE
Improve SEO for gitpod-vs-codespaces

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/website#841] opened 2020-11-23 14:54 UTC
We want to make sure that the [www.gitpod.io/gitpod-vs-codespaces/](https://www.gitpod.io/gitpod-vs-codespaces/) is highly optimized for search engines so that users searching for Codespaces see the page. 

To-do's:

- [ ] mobile speed is really bad according to [page speed](https://developers.google.com/speed/pagespeed/insights/?hl=de&url=https%3A%2F%2Fwww.gitpod.io%2Fgitpod-vs-codespaces%2F&tab=mobile)- Desktop speed is already pretty good. This might already be fixed by #826 and #828

- [ ] the page currently loads 9 javascript files. Could you merge them into one file to improve page speed?

- [x]  a SEO tools says "Some headings occur twice on the page."  I assume it's h4 with "Codespaces" and "Gitpod". Do they need to be in a headline tag? 

- [x]  a SEO tools says "Some anchor texts are used more than once." Could you check that?

- [x] please check the headline order. Can you list h2 ("15x faster loading") before h4 ("Codespaces" and "Gitpod")

- [x] missing a canonical tag: "The canonical can be set in the meta tags or in the response header. If you want this page to be indexed, let the canonical point to this URL. This way, you can clearly indicate which URL is correct."

**Comment by nisarhassan12** [comment] 2020-12-03 16:41
> - [x]  a SEO tools says "Some headings occur twice on the page." I assume it's h4 with "Codespaces" and "Gitpod". Do they need to be in a headline tag?

No they don't have to I have switched the `h4`s with the `div` tag.

> - [x] lease check the headline order.

I have corrected the document outline and this is how it looks:

### Now

![image](https://user-images.githubusercontent.com/46004116/101057108-81e7d280-35ad-11eb-9896-aed5c3fb858e.png)

### Before the changes

![image](https://user-images.githubusercontent.com/46004116/101057301-b78cbb80-35ad-11eb-9319-ab12aa43e1c0.png)

**Comment by nisarhassan12** [comment] 2020-12-03 16:46
> - [ ] a SEO tools says "Some anchor texts are used more than once." Could you check that?

Regarding this. I'm not too sure but I suspect that it is caused by having the word prcing in both of the links. 

![image](https://user-images.githubusercontent.com/46004116/101059660-59ada300-35b0-11eb-80bd-ed99202539cb.png)

Could we try something like `Sources: Pricing Plans for Gitpod and GitHub Codespaces` while having only the product names as links.

**Comment by JohannesLandgraf** [comment] 2020-12-04 13:09
You can even remove the word pricing. Sources: Gitpod, GitHub Codespaces (with respective links)

**Comment by nisarhassan12** [comment] 2020-12-04 16:20
@JohannesLandgraf I have made the requested changes in https://github.com/gitpod-io/website/pull/860 Please have a look again and approve that so we can get it merged.

**Comment by nisarhassan12** [comment] 2020-12-26 18:52
Fixed by https://github.com/gitpod-io/website/pull/860

**Closed by nisarhassan12** 2020-12-26 18:52 UTC
Labels: SEO
