### ISSUE TITLE
Tab component for OS switching

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/website#2285] opened 2022-06-22 11:02 UTC
### Describe your feature request

Similar to how we have the cloud provider component (screenshot below) we should introduce the same for OS (Mac, Linux, Windows) to help us with adding screenshots and instructions on a per OS basis [[1](https://github.com/gitpod-io/website/pull/2274#pullrequestreview-1013830931)].

![image](https://user-images.githubusercontent.com/5528307/175013413-4a1c534d-7830-424f-92c0-feface8e499a.png)

Relates to: 
- https://github.com/gitpod-io/website/issues/2259
- https://github.com/gitpod-io/website/pull/2274#pullrequestreview-1013830931
- https://github.com/gitpod-io/website/issues/2185

Ideally this work will be followed by a full audit of the existing screenshots / GIF's to ensure OS appropriate instructions.

**Comment by filiptronicek** [comment] 2022-09-23 14:45
Duplicate of https://github.com/gitpod-io/website/issues/2752

**Closed by filiptronicek** 2022-09-23 14:45 UTC
Labels: section: docs, docs-enhancement
