### ISSUE TITLE
SEO: Implementation of Canonical Tags (Self-referencing)

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/website#1688] opened 2022-03-01 10:21 UTC
Canonical tags tell search engines that there is a standard resource, or more relevant page, helping to resolve issues with similar or duplicate content. If there isn't a more relevant page concerning the specific topic, the so called self-referencing canonical tag can be implementend on all pages.

**Comment by nisarhassan12** [comment] 2022-03-02 07:09
This issue is a duplicate of https://github.com/gitpod-io/website/issues/661 I'll close that one in favour of this one. 

This issue relates to https://github.com/gitpod-io/website/issues/96 and https://github.com/gitpod-io/website/issues/552#issuecomment-855523715

**Closed** 2022-03-31 05:45 UTC
Labels: seo
