### ISSUE TITLE
Improve the testimonial carousel

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website#143] opened 2021-04-02 18:59 UTC
- [x] Remove the horizontal scrollbar
- [ ] Add drag & drop functionality
- [x] Add dots for navigation visibility + quick navigation.

**Comment by chrifro** [comment] 2022-06-08 12:07
>Add drag & drop functionality

I don't think we need that

**Outstanding to-do's:**
---

- [ ]  Remove the horizontal scrollbar
- [ ] Add dots for navigation visibility + quick navigation  
[mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A9965):
<img width="577" alt="Bildschirmfoto 2022-06-08 um 14 05 36" src="https://user-images.githubusercontent.com/46345125/172612052-651a2c8d-76c6-4700-837d-d838bbb215db.png">

Related issue #2167

**Comment by chrifro** [comment] 2022-08-19 08:20
What's the status here @nisarhassan12 Is is a duplicate of #2240 ?

**Closed** 2022-09-30 09:46 UTC
Labels: a11y, enhancement
