### ISSUE TITLE
Gatsby Example from Gitpod Website Fails

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/website#685] opened 2020-06-18 06:05 UTC
### Describe the bug
the `tasks.command` fails with 
```
yarn run v1.22.4
$ env-cmd -f .env.development gatsby develop --host 0.0.0.0
/bin/sh: 1: env-cmd: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce
open https://gitpod.io/#https://github.com/gitpod-io/website

### Expected behavior
no failure

**Comment by samuelpath** [comment] 2020-08-05 06:53
I'm unable to reproduce the issue:

```
gitpod /workspace/website $ yarn dev --host 0.0.0.0
yarn run v1.22.4
$ env-cmd -f .env.development gatsby develop --host 0.0.0.0
success open and validate gatsby-configs - 0.143s
success load plugins - 1.421s
success onPreInit - 0.017s
success initialize cache - 0.014s
success copy gatsby files - 0.094s
success onPreBootstrap - 0.018s
success createSchemaCustomization - 0.252s
success source and transform nodes - 1.483s
success building schema - 0.707s
success createPages - 0.593s
success createPagesStatefully - 0.322s
success onPreExtractQueries - 0.005ssuccess update schema - 0.060s
success extract queries from components - 0.804s
success write out requires - 0.102s
success write out redirect data - 0.029s
success onPostBootstrap - 0.004s
⠀
info bootstrap finished - 10.534s
⠀
success run queries - 0.125s - 20/20 160.35/s
⠀
You can now view gitpod-website in the browser.
⠀
  Local:            http://localhost:8000/
  On Your Network:  http://10.56.8.186:8000/
⠀
View the GraphQL Playground, an in-browser IDE, to explore your site's data and sche
ma
⠀
  Local:            http://localhost:8000/___graphql
  On Your Network:  http://10.56.8.186:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 10.456s
```

The opening issue mentions: `/bin/sh: 1: env-cmd: not found`.

As if the node package [end-cmd](https://www.npmjs.com/package/env-cmd) wasn't properly installed when the failed command was launched?

**Comment by nisarhassan12** [comment] 2020-09-08 10:10
Closing this as it no longer seems to be relevant.

**Closed by nisarhassan12** 2020-09-08 10:10 UTC
